CREATE DATABASE Diocesis;
USE Diocesis;

CREATE TABLE IF NOT EXISTS Comunidades(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Parroquias(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_Comunidad INT NOT NULL,
    Nombre VARCHAR(100) NOT NULL,
    Fecha_Fundacion DATE,
    Ciudad VARCHAR(50) NOT NULL,
    Direccion VARCHAR(255),
    FOREIGN KEY (ID_Comunidad) REFERENCES Comunidades(ID)
);

CREATE TABLE IF NOT EXISTS Usuarios(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_Parroquia INT NOT NULL,
    Nombre VARCHAR(100) NOT NULL,
    Usuario VARCHAR(50) NOT NULL,
    Pass VARCHAR(100) NOT NULL,
    Rol VARCHAR(30) NOT NULL,
    Fecha_Licencia VARCHAR(10) NOT NULL,
    FOREIGN KEY (ID_Parroquia) REFERENCES Parroquias(ID)
);

CREATE TABLE IF NOT EXISTS Paquetes(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Plazo VARCHAR(20) NOT NULL,
    Meses INT NOT NULL,
    Precio INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Noticias(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Contenido VARCHAR(100) NOT NULL,
    link VARCHAR(100) NOT NULL,
    foto VARCHAR(100) NOT NULL
);